service: aws-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10

# you can overwrite defaults here
  stage: production
  region: us-west-2

plugins:
  - serverless-offline

functions:
  create:
    handler: handler.createUser
    events:
      - http:
          path: create
          method: post
  get:
    handler: handler.getUser
    events:
      - http:
          path: get/{id}
          method: get
  update:
    handler: handler.updateUser
    events:
      - http:
          path: update/{id}
          method: put
  delete:
    handler: handler.deleteUser
    events:
      - http:
          path: delete/{id}
          method: delete

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1