service: user

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 100
  stage: production
  region: us-west-2

plugins:
  - serverless-dynamodb-local
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - test/**
    - .git/**
    - .nyc_output/**
    - coverage/**
    - .editorconfig
    - .eslint*
    - .gitignore
    - .ecosystem.config.js
    - LICENSE
    - README.md
    - tslint.json
  artifact: /tmp/user-artifact.zip


functions:
  getProfile:
    handler: handler.getProfile
    events:
      - http:
          path: profile/{id}
          method: get
      - http:
          path: profile
          method: get
  setProfile:
    handler: handler.setProfile
    events:
      - http:
          path: profile/{id}
          method: put
      - http:
          path: profile
          method: put
  delete:
    handler: handler.deleteUser
    events:
      - http:
          path: delete/{id}
          method: delete
  signup:
    handler: handler.signup
    events:
      - http:
          path: signup
          method: post
  signin:
    handler: handler.signin
    events:
      - http:
          path: signin
          method: post
  signout:
    handler: handler.signout
    events:
      - http:
          path: signout
          method: post

resources:
  Resources:
    users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    nameUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: nameUsers
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    emailUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: emailUsers
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    tokens:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tokens
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  serverless-offline:
    port: 5001
  dynamodb:
    start:
      port: 8000
      dbPath: '/tmp'
      migrate: false
